# -*- Makefile -*-
# YEAH YEAH YEAH

world:
	make -f test8.makefile

#ALIBS= ed25519.a
#A2LIBS=ed25519.a2
#SHLIBS=ed25519.so
#BINS=test test2
#HTML=test.html test2.html
#all: libed25519.a bins # html
#lib%.a: %.a; cp $< $@ && cp $@ ..
#include makefile.inc
